name: Deploy to Production

on:
  push:
    branches:
      - prod # Триггер срабатывает при пуше в ветку prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Проверяем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Настраиваем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0' # Укажите совместимую версию Node.js
          cache: 'npm'

      # Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # Собираем проект
      - name: Build the project
        run: npm run build

      # Деплой на сервер через SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 45.128.204.152
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/front
            git pull origin prod
            npm install
            npm run build
            pm2 restart next
