name: Deploy to Production

on:
  push:
    branches:
      - prod # Запуск при пуше в ветку prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Настройка SSH-агента и добавление ключа
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ADM_SERVER }}

      # Шаг 3: Добавляем сервер в список известных хостов
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 45.128.204.152 >> ~/.ssh/known_hosts

      # Шаг 4: Настройка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0' # Версия Node.js

      # Шаг 5: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 6: Сборка проекта
      - name: Build the project
        run: npm run build

      # Шаг 7: Деплой на сервер через SSH
      - name: Deploy to server
  run: |
    ssh root@45.128.204.152 << 'EOF'
      source ~/.bashrc
      export PATH=$PATH:/root/.nvm/versions/node/v22.13.1/bin
      cd /home/front
      git pull origin prod
      npm install
      npm run build
      pm2 restart next
    EOF
